apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
    {{- range $key, $value := .Values.monitoring.operator.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "jbt-athena-exporter.fullname" . }}-jbt-athena-dashboard
data:
  kafka.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "limit": 100,
            "name": "Annotations & Alerts",
            "showIn": 0,
            "type": "dashboard"
          }
        ]
      },
      "description": "jbt athena exporter from Amazon CloudWatch",
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 84,
      "iteration": 1586977353225,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "description": "Bytes Downloaded from AWS S3 (received from Amazon CloudWatch)",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 6,
            "w": 23,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "s3_athena_bytes_downloaded{bucket=~\"$bucket\"}",
              "legendFormat": "{{`{{bucket}}`}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Bytes Downloaded from AWS S3",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "refresh": false,
      "schemaVersion": 20,
      "style": "dark",
      "tags": [
        "athena"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "text": "Prometheus",
              "value": "Prometheus"
            },
            "hide": 0,
            "includeAll": false,
            "label": null,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "prometheus",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "allValue": null,
            "current": {
              "text": "jbtc-10103-query-result",
              "value": [
                "jbtc-10103-query-result"
              ]
            },
            "datasource": "Prometheus",
            "definition": "label_values(s3_athena_bytes_downloaded{bucket!=\"\"}, bucket)",
            "hide": 0,
            "includeAll": true,
            "label": "bucket",
            "multi": true,
            "name": "bucket",
            "options": [],
            "query": "label_values(s3_athena_bytes_downloaded{bucket!=\"\"}, bucket)",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tags": [],
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-12h",
        "to": "now-1m"
      },
      "timepicker": {
        "hidden": false,
        "nowDelay": "1m",
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "utc",
      "title": "jbt-athena",
      "uid": "dIEw2kqZk",
      "version": 11
    }
