apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-exporter-chart-secret
  labels:
    app: cloudwatch-exporter-chart
type: Opaque
data:
  {{ if .Values.aws.aws_access_key_id }}
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  {{ end }}
  {{ if .Values.aws.aws_secret_access_key }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
  {{ end }}
